=== tawfiqkh/xml/tp1/DTD_xml/releve.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Releve (dateReleve, solde, operations) >
<!ELEMENT dateReleve  (#PCDATA)>
<!ELEMENT solde  (#PCDATA)>
<!ELEMENT operations (operation+) >
<!ELEMENT operation EMPTY>


<!ATTLIST Releve
RIB CDATA #REQUIRED>

<!ATTLIST operations
dateDebut CDATA #REQUIRED>

<!ATTLIST operation
type (CREDIT|DEBIT) 'DEBIT'
date CDATA #REQUIRED
montant CDATA #REQUIRED
description CDATA #REQUIRED
>

=== tawfiqkh/xml/tp1/DTD_xml/releve.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/operation_debit.xslt"?>
<!DOCTYPE Releve SYSTEM "releve.dtd">
<Releve RIB="1234567895854">
    <dateReleve > 12/10/2010 </dateReleve>
    <solde> 99999 </solde>
    <operations dateDebut="01/11/2023">
        <operation type="CREDIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="DEBIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="CREDIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="DEBIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="CREDIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="DEBIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="DEBIT" date="03/11/2023" montant="2000" description="verement"></operation>
        <operation type="DEBIT" date="03/11/2023" montant="2000" description="verement"></operation>

    
    </operations>
</Releve>
